# docker-compose.yml
version: "3.8"
services:
  app:
    build: .
    ports: ["8090:8090"]
    environment:
      - PORT=8090
    command: uvicorn src.Main:app --host 0.0.0.0 --port 8090

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]